"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";
import { Gift, Plus, Trash2 } from "lucide-react";
import { ApiError } from "@/services/apiClient";
import { adminService, type AdminAward, type AdminAwardInput, type AdminAwardType, type AdminCompetition } from "@/services/adminService";
import { statusLabel } from "./adminFormat";
import styles from "./Admin.module.css";

type AwardRow = { key: number; posicaoInicio: string; posicaoFim: string; tipoPremiacao: AdminAwardType; amount: string };
const money = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const numberText = (value: number | null) => value === null ? "" : value.toLocaleString("pt-BR", { maximumFractionDigits: 4 });
const parseDecimal = (value: string) => Number(value.replace(/\./g, "").replace(",", "."));
const toRow = (award: AdminAward, key: number): AwardRow => ({ key, posicaoInicio: String(award.posicaoInicio), posicaoFim: String(award.posicaoFim), tipoPremiacao: award.tipoPremiacao, amount: numberText(award.tipoPremiacao === "VALOR_FIXO" ? award.valor : award.percentual) });
const awardError = (cause: unknown) => cause instanceof ApiError && cause.status === 400 ? "Revise a configuração das premiações." : cause instanceof ApiError && cause.status === 403 ? "Acesso não autorizado." : cause instanceof ApiError && cause.status === 404 ? "Competição não encontrada." : cause instanceof ApiError && cause.status === 409 ? "A premiação não pode mais ser alterada no estado atual da competição." : "Não foi possível carregar ou salvar as premiações.";

export function AwardsManager() {
  const params = useSearchParams(), id = Number(params.get("id")), nextKey = useRef(1);
  const [competition, setCompetition] = useState<AdminCompetition | null>(null), [rows, setRows] = useState<AwardRow[]>([]);
  const [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState(""), [success, setSuccess] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); if (!Number.isSafeInteger(id) || id < 1) { setError("Competição não encontrada."); setLoading(false); return; } try { const [item, awards] = await Promise.all([adminService.getCompetition(id), adminService.getCompetitionAwards(id)]); setCompetition(item); setRows(awards.map((award) => toRow(award, nextKey.current++))); } catch (cause) { setError(awardError(cause)); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  const editable = competition?.status === "RASCUNHO" || competition?.status === "INSCRICOES_ABERTAS";
  const sorted = [...rows].sort((a, b) => Number(a.posicaoInicio) - Number(b.posicaoInicio) || Number(a.posicaoFim) - Number(b.posicaoFim));
  const totalMoney = rows.reduce((sum, row) => row.tipoPremiacao === "VALOR_FIXO" && Number.isFinite(parseDecimal(row.amount)) ? sum + parseDecimal(row.amount) * Math.max(1, Number(row.posicaoFim) - Number(row.posicaoInicio) + 1) : sum, 0);
  const totalPercent = rows.reduce((sum, row) => row.tipoPremiacao === "PERCENTUAL" && Number.isFinite(parseDecimal(row.amount)) ? sum + parseDecimal(row.amount) : sum, 0);
  const update = (key: number, change: Partial<AwardRow>) => setRows((current) => current.map((row) => row.key === key ? { ...row, ...change } : row));
  const add = () => { const position = rows.reduce((max, row) => Math.max(max, Number(row.posicaoFim) || 0), 0) + 1; setRows((current) => [...current, { key: nextKey.current++, posicaoInicio: String(position), posicaoFim: String(position), tipoPremiacao: "VALOR_FIXO", amount: "" }]); setError(""); setSuccess(""); };
  const remove = (key: number) => { setRows((current) => current.filter((row) => row.key !== key)); setSuccess(""); };
  const buildPayload = (): AdminAwardInput[] | null => { let previousEnd = 0, percent = 0; const result: AdminAwardInput[] = []; for (const [index, row] of sorted.entries()) { const start = Number(row.posicaoInicio), end = Number(row.posicaoFim), amount = parseDecimal(row.amount); if (!Number.isSafeInteger(start) || start <= 0 || !Number.isSafeInteger(end) || end < start) { setError("Informe uma faixa de posições válida."); return null; } if (start <= previousEnd) { setError("As faixas de premiação não podem se sobrepor."); return null; } if (competition?.limiteParticipantes !== null && competition?.limiteParticipantes !== undefined && end > competition.limiteParticipantes) { setError(`A posição não pode ultrapassar o limite de ${competition.limiteParticipantes} participantes.`); return null; } if (!Number.isFinite(amount) || (row.tipoPremiacao === "VALOR_FIXO" ? amount < 0 : amount <= 0 || amount > 100)) { setError(row.tipoPremiacao === "VALOR_FIXO" ? "Informe um valor válido para a premiação." : "O percentual deve ser maior que zero e menor ou igual a 100%."); return null; } if (row.tipoPremiacao === "PERCENTUAL") percent += amount; result.push({ posicaoInicio: start, posicaoFim: end, tipoPremiacao: row.tipoPremiacao, valor: row.tipoPremiacao === "VALOR_FIXO" ? amount : null, percentual: row.tipoPremiacao === "PERCENTUAL" ? amount : null, ordem: index }); previousEnd = end; } if (percent > 100) { setError("A soma das premiações percentuais não pode ultrapassar 100%."); return null; } return result; };
  const save = async () => { if (saving || !editable) return; const payload = buildPayload(); if (!payload) return; setSaving(true); setError(""); setSuccess(""); try { const saved = await adminService.updateCompetitionAwards(id, payload); setRows(saved.map((award) => toRow(award, nextKey.current++))); setSuccess("Premiações salvas com sucesso."); } catch (cause) { setError(awardError(cause)); } finally { setSaving(false); } };
  if (loading) return <div className={styles.formLoading} role="status">Carregando premiações...</div>;
  if (!competition) return <div className={styles.formLoading} role="alert">{error || "Competição não encontrada."}<Link href="/admin/competicoes">Voltar para competições</Link></div>;
  return <><header className={`${styles.pageHeader} ${styles.awardsHeader}`}><div><p>COMPETIÇÕES</p><h1>Premiações</h1><span>{competition.nome}</span><div className={styles.awardMeta}><b>{statusLabel(competition.status)}</b><b>{competition.modalidade.nome}</b></div></div><Link href={`/admin/competicoes/editar?id=${id}`}>← Voltar para competição</Link></header>
    {!editable && <p className={styles.readonlyNotice}>A premiação desta competição não pode mais ser alterada porque a fase de configuração foi encerrada.</p>}
    {error && <p className={styles.formError} role="alert">{error}</p>}{success && <p className={styles.formSuccess} role="status">{success}</p>}
    <section className={styles.awardTotals}><div><small>Total em prêmios</small><strong>{money(totalMoney)}</strong></div>{rows.some((row) => row.tipoPremiacao === "PERCENTUAL") && <div><small>Total percentual</small><strong>{totalPercent.toLocaleString("pt-BR")}%</strong></div>}</section>
    <section className={styles.awardPanel}><div className={styles.awardTitle}><Gift /><div><h2>Grade de premiações</h2><p>{rows.length} {rows.length === 1 ? "faixa configurada" : "faixas configuradas"}</p></div></div>
      {!rows.length ? <p className={styles.awardEmpty}>{editable ? "Nenhuma premiação configurada." : "Esta competição não possui premiações configuradas."}</p> : <div className={styles.awardGrid}>{sorted.map((row) => { const position = Number(row.posicaoInicio), medal = position === Number(row.posicaoFim) ? position === 1 ? "🥇" : position === 2 ? "🥈" : position === 3 ? "🥉" : "" : ""; return <article className={`${styles.awardRow} ${position <= 3 ? styles[`awardTop${position}`] : ""}`} key={row.key}><span className={styles.awardPosition}>{medal || `${position}º`}</span><label><span>Posição inicial</span><input aria-label={`Posição inicial ${row.key}`} type="number" min="1" disabled={!editable} value={row.posicaoInicio} onChange={(e) => update(row.key, { posicaoInicio: e.target.value })} /></label><label><span>Posição final</span><input aria-label={`Posição final ${row.key}`} type="number" min="1" disabled={!editable} value={row.posicaoFim} onChange={(e) => update(row.key, { posicaoFim: e.target.value })} /></label><label><span>Tipo</span><select aria-label={`Tipo da premiação ${row.key}`} disabled={!editable} value={row.tipoPremiacao} onChange={(e) => update(row.key, { tipoPremiacao: e.target.value as AdminAwardType, amount: "" })}><option value="VALOR_FIXO">Valor fixo</option><option value="PERCENTUAL">Percentual</option></select></label><label className={styles.awardAmount}><span>{row.tipoPremiacao === "VALOR_FIXO" ? "Valor" : "Percentual"}</span><div><i>{row.tipoPremiacao === "VALOR_FIXO" ? "R$" : "%"}</i><input aria-label={`${row.tipoPremiacao === "VALOR_FIXO" ? "Valor" : "Percentual"} ${row.key}`} inputMode="decimal" disabled={!editable} value={row.amount} onChange={(e) => update(row.key, { amount: e.target.value })} /></div></label>{editable && <button type="button" className={styles.removeAward} onClick={() => remove(row.key)} aria-label={`Remover premiação ${row.key}`}><Trash2 />Remover</button>}</article>; })}</div>}
      {editable && <button type="button" className={styles.addAward} onClick={add}><Plus />Adicionar premiação</button>}
    </section>
    {editable && <div className={styles.formActions}><Link href={`/admin/competicoes/editar?id=${id}`}>Cancelar</Link><button type="button" onClick={() => void save()} disabled={saving}>{saving ? "Salvando..." : "Salvar premiações"}</button></div>}
  </>;
}
