"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { ApiError } from "@/services/apiClient";
import { adminService, type AdminCompetition, type AdminCompetitionPayload, type AdminCompetitionStatus, type AdminLeague, type AdminLeagueModality } from "@/services/adminService";
import { ADMIN_STATUS_LABELS } from "./adminFormat";
import { DuplicateCompetitionDialog } from "./DuplicateCompetitionDialog";
import styles from "./Admin.module.css";

type FormState = { nome: string; slug: string; descricao: string; ligaId: string; ligaModalidadeId: string; rodadaInicio: string; rodadaFim: string; dataInicio: string; dataFim: string; inicioInscricao: string; fimInscricao: string; tipoAcesso: "FREE" | "PAGO"; valorInscricao: string; tipoTaxaPlataforma: "" | "PERCENTUAL" | "VALOR_FIXO"; valorTaxaPlataforma: string; limiteTimesUsuario: string; limiteParticipantes: string; status: AdminCompetitionStatus; visivelApp: boolean; destaque: boolean };
const empty: FormState = { nome: "", slug: "", descricao: "", ligaId: "", ligaModalidadeId: "", rodadaInicio: "", rodadaFim: "", dataInicio: "", dataFim: "", inicioInscricao: "", fimInscricao: "", tipoAcesso: "FREE", valorInscricao: "0,00", tipoTaxaPlataforma: "", valorTaxaPlataforma: "", limiteTimesUsuario: "", limiteParticipantes: "", status: "RASCUNHO", visivelApp: false, destaque: false };
const slugify = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const localDate = (value: string | null) => value ? new Date(value).toISOString().slice(0, 16) : "";
const decimalText = (value: number | null) => value === null ? "" : value.toLocaleString("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const decimal = (value: string) => Number(value.replace(/\./g, "").replace(",", "."));
const integer = (value: string) => value ? Number(value) : null;
const iso = (value: string) => value ? new Date(value).toISOString() : null;
const fromCompetition = (item: AdminCompetition): FormState => ({ nome: item.nome, slug: item.slug, descricao: item.descricao ?? "", ligaId: String(item.liga.id), ligaModalidadeId: String(item.ligaModalidadeId), rodadaInicio: item.rodadaInicio?.toString() ?? "", rodadaFim: item.rodadaFim?.toString() ?? "", dataInicio: localDate(item.dataInicio), dataFim: localDate(item.dataFim), inicioInscricao: localDate(item.inicioInscricao), fimInscricao: localDate(item.fimInscricao), tipoAcesso: item.tipoAcesso as "FREE" | "PAGO", valorInscricao: decimalText(item.valorInscricao), tipoTaxaPlataforma: item.tipoTaxaPlataforma ?? "", valorTaxaPlataforma: decimalText(item.valorTaxaPlataforma), limiteTimesUsuario: item.limiteTimesUsuario?.toString() ?? "", limiteParticipantes: item.limiteParticipantes?.toString() ?? "", status: item.status, visivelApp: item.visivelApp, destaque: item.destaque });
function payload(state: FormState): AdminCompetitionPayload {
  return { ligaModalidadeId: Number(state.ligaModalidadeId), nome: state.nome.trim(), slug: state.slug.trim(), descricao: state.descricao.trim() || null, tipoAcesso: state.tipoAcesso, valorInscricao: state.tipoAcesso === "FREE" ? 0 : decimal(state.valorInscricao), tipoTaxaPlataforma: state.tipoTaxaPlataforma || null, valorTaxaPlataforma: state.tipoTaxaPlataforma ? decimal(state.valorTaxaPlataforma) : null, rodadaInicio: integer(state.rodadaInicio), rodadaFim: integer(state.rodadaFim), dataInicio: iso(state.dataInicio), dataFim: iso(state.dataFim), inicioInscricao: iso(state.inicioInscricao), fimInscricao: iso(state.fimInscricao), limiteTimesUsuario: integer(state.limiteTimesUsuario), limiteParticipantes: integer(state.limiteParticipantes), status: state.status, visivelApp: state.visivelApp, destaque: state.destaque };
}
function friendlyError(cause: unknown) {
  if (!(cause instanceof ApiError)) return "Não foi possível salvar a competição. Tente novamente.";
  if (cause.status === 400) return "Revise os dados informados e tente novamente.";
  if (cause.status === 403) return "Acesso não autorizado para esta operação.";
  if (cause.status === 404) return "Competição não encontrada.";
  if (cause.status === 409 && /slug/i.test(cause.message)) return "Já existe uma competição utilizando este slug.";
  if (cause.status === 409) return "Alguns dados não podem mais ser alterados porque a competição possui inscrições ou está em um estado incompatível.";
  return "Não foi possível salvar a competição. Tente novamente.";
}

export function CompetitionForm({ mode }: { mode: "create" | "edit" }) {
  const router = useRouter(), params = useSearchParams();
  const id = mode === "edit" ? Number(params.get("id")) : null;
  const [form, setForm] = useState<FormState>(empty), [leagues, setLeagues] = useState<AdminLeague[]>([]), [modalities, setModalities] = useState<AdminLeagueModality[]>([]);
  const [source, setSource] = useState<AdminCompetition | null>(null), [duplicating, setDuplicating] = useState(false);
  const [singleRound, setSingleRound] = useState(mode === "create");
  const [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState(""), [success, setSuccess] = useState("");
  const original = useRef<AdminCompetitionPayload | null>(null), slugEdited = useRef(false);
  const loadModalities = useCallback(async (leagueId: number, currentId?: number) => { const result = await adminService.getLeagueModalities(leagueId); setModalities(result.filter((item) => item.ativa || item.ligaModalidadeId === currentId)); }, []);
  const load = useCallback(async () => { setLoading(true); setError(""); try { if (mode === "edit") { if (!Number.isSafeInteger(id) || !id || id < 1) { setError("Competição não encontrada."); return; } const [leagueItems, item] = await Promise.all([adminService.getLeagues(), adminService.getCompetition(id)]); setLeagues(leagueItems); setSource(item); const next = fromCompetition(item); setForm(next); setSingleRound(item.rodadaInicio !== null && item.rodadaInicio === item.rodadaFim); original.current = payload(next); await loadModalities(item.liga.id, item.ligaModalidadeId); } else setLeagues(await adminService.getLeagues()); } catch (cause) { setError(friendlyError(cause)); } finally { setLoading(false); } }, [id, loadModalities, mode]);
  useEffect(() => { void load(); }, [load]);
  const update = <K extends keyof FormState>(key: K, value: FormState[K]) => setForm((current) => ({ ...current, [key]: value }));
  const selectLeague = async (value: string) => { setForm((current) => ({ ...current, ligaId: value, ligaModalidadeId: "" })); setModalities([]); if (value) try { await loadModalities(Number(value)); } catch { setError("Não foi possível carregar as modalidades desta liga."); } };
  const validate = () => {
    if (!form.nome.trim() || !form.slug.trim() || !form.ligaModalidadeId) return "Preencha nome, slug, liga e modalidade.";
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(form.slug)) return "Use apenas letras minúsculas, números e hífens no slug.";
    if (form.tipoAcesso === "PAGO" && (!(decimal(form.valorInscricao) > 0))) return "Informe um valor de inscrição maior que zero para competições pagas.";
    if (form.tipoTaxaPlataforma && (!Number.isFinite(decimal(form.valorTaxaPlataforma)) || decimal(form.valorTaxaPlataforma) < 0)) return "Informe um valor válido para a taxa da plataforma.";
    if (form.tipoTaxaPlataforma === "PERCENTUAL" && decimal(form.valorTaxaPlataforma) > 100) return "A taxa percentual deve estar entre 0 e 100.";
    if ([form.rodadaInicio, form.rodadaFim, form.limiteTimesUsuario, form.limiteParticipantes].some((value) => value && (!Number.isInteger(Number(value)) || Number(value) <= 0))) return "Rodadas e limites devem ser números inteiros positivos.";
    if (form.rodadaInicio && form.rodadaFim && Number(form.rodadaFim) < Number(form.rodadaInicio)) return "A rodada final não pode ser anterior à rodada inicial.";
    const dateFields = ["dataInicio", "dataFim", "inicioInscricao", "fimInscricao"] as const;
    // Compare com o mesmo snapshot normalizado usado para montar o PATCH parcial.
    const validateDates = mode === "create" || dateFields.some((key) => iso(form[key]) !== original.current?.[key]);
    if (validateDates) {
      if (form.dataInicio && form.dataFim && form.dataFim < form.dataInicio) return "A data final não pode ser anterior à data inicial.";
      if (form.inicioInscricao && form.fimInscricao && form.fimInscricao < form.inicioInscricao) return "O fim das inscrições não pode ser anterior ao início.";
      if (form.fimInscricao && form.dataInicio && form.fimInscricao > form.dataInicio) return "As inscrições devem terminar antes do início da competição.";
    }
    return "";
  };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (saving) return; const validation = validate(); if (validation) { setError(validation); return; } setSaving(true); setError(""); setSuccess(""); try { const complete = payload(form); if (mode === "create") { const created = await adminService.createCompetition(complete); setSuccess("Competição criada com sucesso."); router.replace(`/admin/competicoes/editar?id=${created.id}`); } else if (id) { const changed = Object.fromEntries(Object.entries(complete).filter(([key, value]) => JSON.stringify(value) !== JSON.stringify(original.current?.[key as keyof AdminCompetitionPayload]))) as Partial<AdminCompetitionPayload>; if (Object.keys(changed).length) { const saved = await adminService.updateCompetition(id, changed); const next = fromCompetition(saved); setSource(saved); setForm(next); original.current = payload(next); } setSuccess("Alterações salvas com sucesso."); } } catch (cause) { setError(friendlyError(cause)); } finally { setSaving(false); } };
  if (loading) return <div className={styles.formLoading} role="status">Carregando formulário...</div>;
  if (error && mode === "edit" && (!Number.isSafeInteger(id) || !id || id < 1)) return <div className={styles.formLoading} role="alert">{error}<Link href="/admin/competicoes">Voltar para competições</Link></div>;
  const section = (title: string, children: React.ReactNode) => <fieldset className={styles.formSection}><legend>{title}</legend><div className={styles.formGrid}>{children}</div></fieldset>;
  const field = (label: string, control: React.ReactNode, wide = false, hint?: string) => <label className={wide ? styles.wideField : ""}><span>{label}</span>{control}{hint && <small>{hint}</small>}</label>;
  return <><header className={styles.pageHeader}><p>COMPETIÇÕES</p><h1>{mode === "create" ? "Nova competição" : "Editar competição"}</h1><span>{mode === "create" ? "Configure uma nova disputa do POINT FFC." : "Atualize os dados permitidos desta competição."}</span></header><form className={styles.competitionForm} onSubmit={submit} noValidate>
    {error && <p className={styles.formError} role="alert">{error}</p>}{success && <p className={styles.formSuccess} role="status">{success}</p>}
    {section("1. Identificação", <>{field("Nome", <input value={form.nome} onChange={(e) => { update("nome", e.target.value); if (!slugEdited.current && mode === "create") update("slug", slugify(e.target.value)); }} required />)}{field("Slug", <input value={form.slug} onChange={(e) => { slugEdited.current = true; update("slug", e.target.value); }} required />, false, "Usado nas URLs e deve ser único.")}{field("Descrição", <textarea value={form.descricao} onChange={(e) => update("descricao", e.target.value)} rows={3} />, true)}</>)}
    {section("2. Liga e modalidade", <>{field("Liga", <select value={form.ligaId} onChange={(e) => void selectLeague(e.target.value)} required><option value="">Selecione a liga</option>{leagues.map((league) => <option key={league.id} value={league.id}>{league.nome}</option>)}</select>)}{field("Modalidade", <select value={form.ligaModalidadeId} onChange={(e) => update("ligaModalidadeId", e.target.value)} disabled={!form.ligaId} required><option value="">Selecione a modalidade</option>{modalities.map((item) => <option key={item.ligaModalidadeId} value={item.ligaModalidadeId} disabled={!item.ativa && String(item.ligaModalidadeId) !== form.ligaModalidadeId}>{item.nome}{!item.ativa ? " (inativa)" : ""}</option>)}</select>)}</>)}
    {section("3. Período e rodada", <>{field("Rodada inicial", <input type="number" min="1" value={form.rodadaInicio} onChange={(e) => { update("rodadaInicio", e.target.value); if (singleRound) update("rodadaFim", e.target.value); }} />)}{field("Rodada final", <input type="number" min="1" value={form.rodadaFim} disabled={singleRound} onChange={(e) => update("rodadaFim", e.target.value)} />, false, singleRound ? "Mantida igual à rodada inicial." : undefined)}<label className={`${styles.roundToggle} ${styles.wideField}`}><input type="checkbox" checked={singleRound} onChange={(e) => { setSingleRound(e.target.checked); if (e.target.checked) update("rodadaFim", form.rodadaInicio); }} />Competição de rodada única</label>{field("Data de início", <input type="datetime-local" value={form.dataInicio} onChange={(e) => update("dataInicio", e.target.value)} />)}{field("Data de fim", <input type="datetime-local" value={form.dataFim} onChange={(e) => update("dataFim", e.target.value)} />)}</>)}
    {section("4. Inscrições", <>{field("Início das inscrições", <input type="datetime-local" value={form.inicioInscricao} onChange={(e) => update("inicioInscricao", e.target.value)} />)}{field("Fim das inscrições", <input type="datetime-local" value={form.fimInscricao} onChange={(e) => update("fimInscricao", e.target.value)} />, false, "Deve ocorrer antes do início da competição.")}</>)}
    {section("5. Valores e taxa", <>{field("Tipo de acesso", <select value={form.tipoAcesso} onChange={(e) => { const type = e.target.value as "FREE" | "PAGO"; update("tipoAcesso", type); if (type === "FREE") update("valorInscricao", "0,00"); }}><option value="FREE">Grátis</option><option value="PAGO">Pago</option></select>)}{field("Valor da inscrição", <div className={styles.moneyInput}><span>R$</span><input aria-label="Valor da inscrição" inputMode="decimal" value={form.valorInscricao} disabled={form.tipoAcesso === "FREE"} onChange={(e) => update("valorInscricao", e.target.value)} /></div>)}{field("Taxa da plataforma", <select value={form.tipoTaxaPlataforma} onChange={(e) => { const type = e.target.value as FormState["tipoTaxaPlataforma"]; update("tipoTaxaPlataforma", type); if (!type) update("valorTaxaPlataforma", ""); }}><option value="">Sem taxa</option><option value="PERCENTUAL">Percentual</option><option value="VALOR_FIXO">Valor fixo</option></select>)}{field(form.tipoTaxaPlataforma === "PERCENTUAL" ? "Percentual da taxa" : "Valor da taxa", <div className={styles.moneyInput}><span>{form.tipoTaxaPlataforma === "PERCENTUAL" ? "%" : "R$"}</span><input aria-label="Valor da taxa" inputMode="decimal" value={form.valorTaxaPlataforma} disabled={!form.tipoTaxaPlataforma} onChange={(e) => update("valorTaxaPlataforma", e.target.value)} /></div>)}</>)}
    {section("6. Limites", <>{field("Limite de times por usuário", <input type="number" min="1" value={form.limiteTimesUsuario} onChange={(e) => update("limiteTimesUsuario", e.target.value)} placeholder="Sem limite" />, false, "Deixe vazio para não limitar.")}{field("Limite de participantes", <input type="number" min="1" value={form.limiteParticipantes} onChange={(e) => update("limiteParticipantes", e.target.value)} placeholder="Sem limite" />, false, "Deixe vazio para não limitar.")}</>)}
    {section("7. Publicação", <>{field("Status", <select value={form.status} onChange={(e) => update("status", e.target.value as AdminCompetitionStatus)}>{Object.entries(ADMIN_STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>)}<div className={styles.checks}><label><input type="checkbox" checked={form.visivelApp} onChange={(e) => update("visivelApp", e.target.checked)} />Visível no aplicativo</label><label><input type="checkbox" checked={form.destaque} onChange={(e) => update("destaque", e.target.checked)} />Destaque</label></div></>)}
    {mode === "edit" && id && <div className={styles.secondaryActions}><button type="button" onClick={() => setDuplicating(true)}>Duplicar</button><Link className={styles.awardsCta} href={`/admin/competicoes/premiacoes?id=${id}`}>Configurar premiações</Link></div>}
    <div className={styles.formActions}><Link href="/admin/competicoes">{mode === "create" ? "Cancelar" : "Voltar"}</Link><button type="submit" disabled={saving}>{saving ? "Salvando..." : mode === "create" ? "Criar competição" : "Salvar alterações"}</button></div>
  </form>{duplicating && source && <DuplicateCompetitionDialog source={source} close={() => setDuplicating(false)} />}</>;
}
