"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/contexts/AuthContext";
import { Dialog } from "@/components/ui/Dialog";
import { teamService } from "@/services/teamService";
import type { CartolaTeam } from "@/types/team";
import { blockMessages, pointLeagueService, type CompetitionSummary, type Entry, type RankingEntry } from "@/services/pointLeagueService";
import styles from "./PointCompetition.module.css";

type Tab = "Visão geral" | "Meus times" | "Participantes" | "Premiação" | "Ranking";
const tabs: Tab[] = ["Visão geral", "Meus times", "Participantes", "Premiação", "Ranking"];
const date = (value: string | null) => value ? new Date(value).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" }) : "Não informado";
const score = (value: number | null) => value === null ? "Sem pontuação" : value.toLocaleString("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const position = (value: number | null) => value === null ? "—" : `${value}º`;
const message = (error: unknown) => error instanceof Error ? error.message : "Não foi possível carregar os dados.";
function Entries({ entries, ownIds = new Set<number>(), ranking = false }: { entries: (Entry | RankingEntry)[]; ownIds?: Set<number>; ranking?: boolean }) {
  if (!entries.length) return <p className={styles.empty}>{ranking ? "Ranking ainda não disponível." : "Nenhum time encontrado."}</p>;
  return <div className={styles.entries}>{entries.map((entry) => { const own = ownIds.has(entry.id) || ("inscricaoId" in entry && ownIds.has(entry.inscricaoId)); const movement = entry.posicao !== null && entry.posicaoAnterior !== null ? entry.posicaoAnterior - entry.posicao : null; return <article className={`${styles.entry} ${own ? styles.own : ""}`} key={entry.id ?? (entry as RankingEntry).inscricaoId}><strong>{position(entry.posicao)}</strong>{ranking && <small>{movement === null || movement === 0 ? "—" : movement > 0 ? `↑ ${movement}` : `↓ ${-movement}`}</small>}{entry.escudoUrl && <img src={entry.escudoUrl} alt="" />}<div><strong>{entry.nomeTime}{own && " · Meu time"}</strong><small>{entry.nomeCartoleiro ?? "Cartoleiro não informado"}</small></div><span>{score(entry.pontuacao)}</span>{!ranking && "posicaoAnterior" in entry && <small>Anterior: {position(entry.posicaoAnterior)}</small>}</article>; })}</div>;
}
export function PointCompetitionPage({ id }: { id: number }) {
  const router = useRouter();
  const { isAuthenticated, isLoading: authLoading } = useAuth();
  const [summary, setSummary] = useState<CompetitionSummary | null>(null), [tab, setTab] = useState<Tab>("Visão geral");
  const [entries, setEntries] = useState<Entry[]>([]), [ranking, setRanking] = useState<RankingEntry[]>([]), [teams, setTeams] = useState<CartolaTeam[]>([]);
  const [loading, setLoading] = useState(true), [sectionLoading, setSectionLoading] = useState(false), [modal, setModal] = useState(false), [busy, setBusy] = useState(false);
  const [error, setError] = useState(""), [sectionError, setSectionError] = useState(""), [feedback, setFeedback] = useState(""), [selected, setSelected] = useState<number | null>(null);
  const loadSummary = useCallback(async () => setSummary(await pointLeagueService.summary(id, isAuthenticated)), [id, isAuthenticated]);
  useEffect(() => { if (authLoading) return; let active = true; setLoading(true); setError(""); pointLeagueService.summary(id, isAuthenticated).then((data) => { if (active) setSummary(data); }).catch((e) => { if (active) setError(message(e)); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [id, isAuthenticated, authLoading]);
  const loadTab = useCallback(async (current: Tab) => { setSectionLoading(true); setSectionError(""); try { if (current === "Meus times" && isAuthenticated) setEntries(await pointLeagueService.myEntries(id)); if (current === "Participantes") setEntries(await pointLeagueService.participants(id)); if (current === "Ranking") setRanking((await pointLeagueService.ranking(id)).ranking); } catch (e) { setSectionError(message(e)); } finally { setSectionLoading(false); } }, [id, isAuthenticated]);
  useEffect(() => { if (!summary) return; void loadTab(tab); }, [tab, summary, loadTab]);
  const openModal = async () => { if (!isAuthenticated) { router.push(`/login?next=${encodeURIComponent(`/competicoes?id=${id}`)}`); return; } if (!summary?.usuario?.podeInscrever) return; setModal(true); setSectionError(""); try { setTeams(await teamService.buscarMeusTimes()); } catch (e) { setSectionError(message(e)); } };
  const enroll = async () => { if (selected === null || busy || !summary?.usuario?.podeInscrever) return; setBusy(true); setSectionError(""); try { await pointLeagueService.enroll(id, selected); setModal(false); setSelected(null); setFeedback("Time inscrito com sucesso!"); await loadSummary(); if (tab === "Meus times" || tab === "Participantes" || tab === "Ranking") await loadTab(tab); } catch (e) { setSectionError(message(e)); } finally { setBusy(false); } };
  const ownIds = new Set(summary?.minhasInscricoes?.map((item) => item.id) ?? []);
  return <main className={`page-shell ${styles.shell}`}><Link href="/ligas/point-ffc">← POINT FFC</Link>{loading ? <p role="status">Carregando competição...</p> : error ? <p role="alert" className={styles.error}>{error}</p> : summary && <>
    <header className={styles.hero}><div><p className="eyebrow">{summary.liga.nome} · Rodada {summary.competicao.rodadaInicio ?? "—"}</p><h1>{summary.competicao.nome}</h1><p>{summary.competicao.descricao}</p></div><span>{summary.competicao.status}</span></header>
    {feedback && <p role="status" className={styles.success}>{feedback}</p>}
    <nav className={styles.tabs} aria-label="Seções da competição">{tabs.map((item) => <button type="button" key={item} className={tab === item ? styles.active : ""} onClick={() => setTab(item)}>{item}</button>)}</nav>
    {tab === "Visão geral" && <section className={styles.panel}><div className={styles.facts}><p><small>Acesso</small><strong>{summary.competicao.tipoAcesso === "FREE" ? "FREE" : summary.competicao.tipoAcesso}</strong></p><p><small>Inscritos</small><strong>{summary.inscritos.quantidade}</strong></p><p><small>Limite por usuário</small><strong>{summary.competicao.limiteTimesUsuario ?? "Sem limite"}</strong></p><p><small>Inscrições</small><strong>{date(summary.competicao.inicioInscricao)} até {date(summary.competicao.fimInscricao)}</strong></p></div><p>Premiação: {summary.premiacao.length ? `${summary.premiacao.length} faixa(s) cadastrada(s)` : "Ainda não definida"}</p>{isAuthenticated && summary.usuario && <p>Seus times: {summary.usuario.quantidadeTimesInscritos}{summary.usuario.limiteTimesUsuario !== null && ` / ${summary.usuario.limiteTimesUsuario}`} · Melhor posição: {position(summary.usuario.melhorPosicaoUsuario)} · Melhor pontuação: {score(summary.usuario.melhorPontuacaoUsuario)}</p>}<button className={styles.primary} type="button" onClick={() => void openModal()} disabled={isAuthenticated && !summary.usuario?.podeInscrever}>{isAuthenticated ? "Inscrever time" : "Entre para inscrever time"}</button>{isAuthenticated && summary.usuario && !summary.usuario.podeInscrever && <p className={styles.notice}>{blockMessages[summary.usuario.motivoBloqueio ?? ""] ?? "Inscrição indisponível no momento."}</p>}<button type="button" className={styles.linkButton} onClick={() => setTab("Ranking")}>Ver ranking →</button></section>}
    {tab === "Premiação" && <section className={styles.panel}><h2>Premiação</h2>{summary.premiacao.length ? summary.premiacao.map((prize) => <p key={prize.ordem}>{prize.posicaoInicio}º{prize.posicaoFim !== prize.posicaoInicio && ` a ${prize.posicaoFim}º`} · {prize.tipoPremiacao}{prize.valor !== null && ` · ${prize.valor.toLocaleString("pt-BR")}`}{prize.percentual !== null && ` · ${prize.percentual}%`}</p>) : <p>Premiação ainda não definida para esta competição.</p>}</section>}
    {tab === "Meus times" && !isAuthenticated ? <section className={styles.panel}><p>Entre para acompanhar seus times inscritos.</p><Link href="/login">Fazer login</Link></section> : null}
    {sectionError && <p role="alert" className={styles.error}>{sectionError}</p>}
    {sectionLoading && ["Meus times", "Participantes", "Ranking"].includes(tab) ? <p role="status">Carregando...</p> : tab === "Meus times" && isAuthenticated ? <section className={styles.panel}><h2>Meus times</h2>{entries.length ? <Entries entries={entries} /> : <p className={styles.empty}>Você ainda não inscreveu times nesta competição.</p>}</section> : tab === "Participantes" ? <section className={styles.panel}><h2>Participantes</h2><Entries entries={entries} /></section> : tab === "Ranking" ? <section className={styles.panel}><div className={styles.heading}><h2>Ranking</h2><button type="button" onClick={() => void loadTab("Ranking")}>Atualizar</button></div><Entries entries={ranking} ownIds={ownIds} ranking /></section> : null}
    {modal && <Dialog title="Inscrever time" close={() => !busy && setModal(false)} busy={busy}><p>Selecione um dos seus times em Meus Times.</p>{teams.length ? <div className={styles.choices}>{teams.map((team) => <label key={team.timeId}><input type="radio" name="team" checked={selected === team.timeId} onChange={() => setSelected(team.timeId)} disabled={busy || summary.minhasInscricoes?.some((entry) => entry.timeIdCartola === team.timeId)} />{team.escudoUrl && <img src={team.escudoUrl} alt="" />}{team.nome}</label>)}</div> : <p>Nenhum time vinculado. <Link href="/meus-times">Adicionar em Meus Times</Link></p>}<div className={styles.actions}><button type="button" onClick={() => setModal(false)} disabled={busy}>Cancelar</button><button type="button" className={styles.primary} disabled={busy || selected === null} onClick={() => void enroll()}>{busy ? "Inscrevendo..." : "Confirmar inscrição FREE"}</button></div></Dialog>}
  </>}</main>;
}
