"use client";
import Link from "next/link";
import { ArrowRight, Bot, ImageOff, MapPin, Shield, Trophy, Users } from "lucide-react";
import { featuredOdds, oddsByMatchId, wizardAttacks, wizardCleanSheets, wizardGoals, wizardTips } from "@/data/dashboard";
import { leagueService } from "@/services/leagueService";
import { formatCurrency } from "@/lib/format";
import { escudoClube, formatarPartida, nomeClube, obterClube, ordenarPartidas, statusPartida } from "@/lib/cartola";
import { useCartolaDashboard } from "@/hooks/useCartolaDashboard";
import { CartolaMarketStatus } from "./CartolaMarketStatus";
import { TopAthletes } from "./TopAthletes";
import { Odds } from "./Odds";
import { GeneralRanking } from "./GeneralRanking";
import styles from "./Dashboard.module.css";
export function CartolaDashboard(){
 const {dashboard,loading,error,stale,atualizar,athletes,athletesLoading,athletesError,statisticsMatches}=useCartolaDashboard(); const featured=leagueService.getFeatured();const leagues=leagueService.getOpen().filter(item=>!item.featured).slice(0,3);
 if(!dashboard&&loading)return <div className={styles.shell}><div className={styles.pageTitle}><h1>Dashboard</h1></div><div className={styles.dashboardSkeleton} aria-label="Carregando dados da rodada"/></div>;
 if(!dashboard)return <div className={styles.shell}><div className={styles.pageTitle}><h1>Dashboard</h1></div><section className={styles.loadError}><p>Não foi possível atualizar os dados da rodada.</p><button type="button" onClick={atualizar}>Tentar novamente</button></section></div>;
 const round=dashboard.rodada;const matches=ordenarPartidas(dashboard.partidas).slice(0,5);const statsRound=dashboard.mercadoAberto?Math.max(1,round-1):round;const statsMatches=statisticsMatches??[];const scoredMatches=statsMatches.filter(match=>match.placar_oficial_mandante!=null&&match.placar_oficial_visitante!=null);const confirmedGoals=scoredMatches.reduce((total,match)=>total+match.placar_oficial_mandante!+match.placar_oficial_visitante!,0);const realRoundStatistics=[{label:"Jogos",value:String(statsMatches.length)},{label:"Com placar",value:String(scoredMatches.length)},{label:"Gols confirmados",value:String(confirmedGoals)},{label:"Média de gols",value:scoredMatches.length?(confirmedGoals/scoredMatches.length).toLocaleString("pt-BR",{minimumFractionDigits:1,maximumFractionDigits:2}):"—"}];
 return <div className={styles.shell}><div className={styles.pageTitle}><h1>Dashboard</h1><span>Rodada {round}</span></div>
 {featured&&<section className={styles.feature}><div><small>Liga destaque</small><div className={styles.featureIdentity}><span><Trophy/></span><div><h2>{featured.name}</h2><p>Rodada {round}</p></div></div></div><div className={styles.featurePrize}><small>Premiação</small><strong>{formatCurrency(featured.prizePool)}</strong><Link href={`/ligas/${featured.id}`}>Ver liga</Link></div></section>}
 {stale&&<p className={styles.staleNotice}>Dados temporariamente desatualizados.</p>}{error&&<p className={styles.refreshError}>Não foi possível buscar a atualização mais recente.</p>}
 <CartolaMarketStatus mercado={dashboard.mercado} aberto={dashboard.mercadoAberto} aoVivo={dashboard.bolaRolando} atualizar={atualizar}/>
 <section className={styles.cardSection}><div className={styles.sectionHead}><h2>Jogos da rodada</h2><Link href="/central-da-rodada">Ver todos <ArrowRight/></Link></div>{matches.length?<div className={styles.matchList}>{matches.map((game,index)=>{const home=obterClube(dashboard.clubes,game.clube_casa_id),away=obterClube(dashboard.clubes,game.clube_visitante_id),schedule=formatarPartida(game),matchStatus=statusPartida(game),scored=game.placar_oficial_mandante!=null&&game.placar_oficial_visitante!=null;return <Link href={`/jogos/?partida=${game.partida_id}`} className={styles.match} key={game.partida_id} aria-label={`Ver detalhes de ${nomeClube(home,game.clube_casa_id)} contra ${nomeClube(away,game.clube_visitante_id)}`}><div className={styles.matchSchedule}>{schedule.completa}{matchStatus&&<span className={matchStatus.live?styles.matchLive:styles.matchFinished}>{matchStatus.live&&<i/>}{matchStatus.label}</span>}</div><div className={styles.matchup}><Club club={home} id={game.clube_casa_id}/><span className={styles.versus}>{scored?`${game.placar_oficial_mandante} × ${game.placar_oficial_visitante}`:schedule.hora}</span><Club club={away} id={game.clube_visitante_id}/></div><p className={styles.venue}><MapPin/> {game.local||"Local a definir"}</p><Odds odds={oddsByMatchId[game.partida_id]??featuredOdds[index]} demonstrative={!oddsByMatchId[game.partida_id]}/></Link>})}</div>:<p className={styles.emptyMatches}>Nenhuma partida disponível para esta rodada.</p>}</section>
 <section className={styles.mago}><div className={styles.magoHead}><div className={styles.magoAvatar}><Bot/></div><div><small>Mago IA</small><h2>Inteligência da rodada {round}</h2></div><Link href="/central-da-rodada">Ver análise completa <ArrowRight/></Link></div><div className={styles.magoPanels}><article><h3>Melhores SG</h3>{wizardCleanSheets.map((x,i)=><p key={x.team}><span>{i+1}º <b>{x.team}</b></span><strong>{x.value}</strong></p>)}</article><article><h3>Expectativa de gols (xG)</h3>{wizardGoals.map((x,i)=><p key={x.team}><span>{i+1}º <b>{x.team}</b></span><strong>{x.value}</strong></p>)}</article><article><h3>Ataques em alta</h3>{wizardAttacks.map((x,i)=><p key={x.team}><span>{i+1}º <b>{x.team}</b></span><strong>{x.value}</strong></p>)}</article><article className={styles.tips}><h3>Dicas do Mago</h3>{wizardTips.map(x=><p key={x}>• {x}</p>)}</article></div></section>
 <section className={styles.leagues}><div className={styles.sectionHead}><h2>{dashboard.mercadoAberto?"Ligas disponíveis para jogar":"Ligas em andamento"}</h2><Link href="/ligas">Ver todas <ArrowRight/></Link></div><div className={styles.leagueGrid}>{leagues.map(league=><article className={styles.league} key={league.id}><div className={styles.leagueIdentity}><span><Shield/></span><div><h3>{league.name}</h3><small>Rodada {round}</small></div></div><dl><div><dt>Premiação</dt><dd>{formatCurrency(league.prizePool)}</dd></div><div><dt>Entrada</dt><dd>{formatCurrency(league.entryFee)}</dd></div><div><dt>Participantes</dt><dd>{league.currentParticipants}</dd></div></dl><Link href={`/ligas/${league.id}`}>{dashboard.mercadoAberto?"Jogar":"Acompanhar"}</Link></article>)}</div></section>
 <GeneralRanking round={round}/>
 <TopAthletes data={athletes} round={dashboard.mercadoAberto?Math.max(1,round-1):round} live={!dashboard.mercadoAberto&&dashboard.bolaRolando} loading={athletesLoading} error={athletesError} firstRound={dashboard.mercadoAberto&&round===1}/>
 <section className={styles.statsSection}><div className={styles.sectionHead}><h2>Estatísticas da rodada {statsRound}</h2><Link href="/central-da-rodada">Ver mais <ArrowRight/></Link></div><div className={styles.stats}>{realRoundStatistics.map((x,i)=><article key={x.label}>{i===0?<Trophy/>:<Users/>}<div><strong>{x.value}</strong><small>{x.label}</small></div></article>)}</div></section></div>;
}
function Club({club,id}:{club:ReturnType<typeof obterClube>;id:number}){const name=nomeClube(club,id),shield=escudoClube(club);return <div className={styles.team}>{shield&&<img src={shield} alt={`Escudo do ${club.nome??name}`} width="58" height="58" onError={event=>{event.currentTarget.style.display="none";event.currentTarget.nextElementSibling?.removeAttribute("hidden");}}/>}<span className={styles.shieldFallback} hidden={Boolean(shield)} aria-hidden="true"><ImageOff/></span><strong title={club.nome??name}>{name}</strong></div>}
