import Image from "next/image";
import Link from "next/link";
import {ArrowRight,Bot,MapPin,Shield,Trophy,Users} from "lucide-react";
import {marketStatus,oddsByMatchId,roundStatistics,wizardAttacks,wizardCleanSheets,wizardGoals,wizardTips} from "@/data/dashboard";
import {leagueService} from "@/services/leagueService";
import {matchService} from "@/services/matchService";
import {formatCurrency} from "@/lib/format";
import {MarketStatus} from "./MarketStatus";
import {Odds} from "./Odds";
import styles from "./Dashboard.module.css";
function schedule(value:string){const date=new Date(value.replace(" ","T"));return `${date.toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"})} • ${date.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}`}
export function Dashboard(){const matches=matchService.getCurrentRound();const featured=leagueService.getFeatured();const leagues=leagueService.getOpen().filter(item=>!item.featured).slice(0,3);return <div className={styles.shell}>
 <div className={styles.pageTitle}><h1>Dashboard</h1><span>Rodada {marketStatus.round}</span></div>
 {featured&&<section className={styles.feature}><div><small>Liga destaque</small><div className={styles.featureIdentity}><span><Trophy/></span><div><h2>{featured.name}</h2><p>Rodada {marketStatus.round}</p></div></div></div><div className={styles.featurePrize}><small>Premiação</small><strong>{formatCurrency(featured.prizePool)}</strong><Link href={`/ligas/${featured.id}`}>Ver liga</Link></div></section>}
 <MarketStatus status={marketStatus}/>
 <section className={styles.cardSection}><div className={styles.sectionHead}><h2>Jogos da rodada</h2><Link href="/jogos">Ver todos <ArrowRight/></Link></div><div className={styles.matchList}>{matches.matches.slice(0,5).map(game=>{const scored=game.homeScore!==null&&game.awayScore!==null;return <article className={styles.match} key={game.id}><div className={styles.matchSchedule}>{schedule(game.date)}</div><div className={styles.matchup}><div className={styles.team}><Image src={game.home.shieldUrl} alt={`Escudo ${game.home.abbreviation}`} width={58} height={58} unoptimized/><strong>{game.home.abbreviation}</strong></div><span className={styles.versus}>{scored?`${game.homeScore} × ${game.awayScore}`:"– × –"}</span><div className={styles.team}><Image src={game.away.shieldUrl} alt={`Escudo ${game.away.abbreviation}`} width={58} height={58} unoptimized/><strong>{game.away.abbreviation}</strong></div></div><p className={styles.venue}><MapPin/> {game.venue}</p><Odds odds={oddsByMatchId[game.id]}/></article>})}</div></section>
 <section className={styles.mago}><div className={styles.magoHead}><div className={styles.magoAvatar}><Bot/></div><div><small>Mago IA</small><h2>Inteligência da rodada {marketStatus.round}</h2></div><Link href="/central-da-rodada">Ver análise completa <ArrowRight/></Link></div><div className={styles.magoPanels}><article><h3>Melhores SG</h3>{wizardCleanSheets.map((item,index)=><p key={item.team}><span>{index+1}º <b>{item.team}</b></span><strong>{item.value}</strong></p>)}</article><article><h3>Expectativa de gols (xG)</h3>{wizardGoals.map((item,index)=><p key={item.team}><span>{index+1}º <b>{item.team}</b></span><strong>{item.value}</strong></p>)}</article><article><h3>Ataques em alta</h3>{wizardAttacks.map((item,index)=><p key={item.team}><span>{index+1}º <b>{item.team}</b></span><strong>{item.value}</strong></p>)}</article><article className={styles.tips}><h3>Dicas do Mago</h3>{wizardTips.map(tip=><p key={tip}>• {tip}</p>)}</article></div></section>
 <section className={styles.leagues}><div className={styles.sectionHead}><h2>{marketStatus.isOpen?"Ligas disponíveis para jogar":"Ligas em andamento"}</h2><Link href="/ligas">Ver todas <ArrowRight/></Link></div><div className={styles.leagueGrid}>{leagues.map(league=><article className={styles.league} key={league.id}><div className={styles.leagueIdentity}><span><Shield/></span><div><h3>{league.name}</h3><small>Rodada {marketStatus.round}</small></div></div><dl><div><dt>Premiação</dt><dd>{formatCurrency(league.prizePool)}</dd></div><div><dt>Entrada</dt><dd>{formatCurrency(league.entryFee)}</dd></div><div><dt>Participantes</dt><dd>{league.currentParticipants}</dd></div></dl><Link href={`/ligas/${league.id}`}>{marketStatus.isOpen?"Jogar":"Acompanhar"}</Link></article>)}</div></section>
 <section className={styles.statsSection}><div className={styles.sectionHead}><h2>Estatísticas da rodada</h2><Link href="/central-da-rodada">Ver mais <ArrowRight/></Link></div><div className={styles.stats}>{roundStatistics.map((item,index)=><article key={item.label}>{index===0?<Trophy/>:<Users/>}<div><strong>{item.value}</strong><small>{item.label}</small></div></article>)}</div></section>
 </div>}
