"use client";
import Link from "next/link";
import { ArrowRight, ImageOff, Sparkles } from "lucide-react";
import type { CartolaClub, CartolaScoredAthlete, CartolaScoredAthletesResponse } from "@/types/cartola";
import { escudoClube, nomeClube } from "@/lib/cartola";
import styles from "./TopAthletes.module.css";
const positions:Record<number,string>={1:"GOL",2:"LAT",3:"ZAG",4:"MEI",5:"ATA",6:"TEC"};
const points=new Intl.NumberFormat("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2});
export function TopAthletes({data,round,live,loading,error,firstRound}:{data:CartolaScoredAthletesResponse|null;round:number;live:boolean;loading:boolean;error:string|null;firstRound:boolean}){
 const athletes=data?Object.entries(data.atletas).map(([id,athlete])=>({id,athlete})).sort((a,b)=>b.athlete.pontuacao-a.athlete.pontuacao).slice(0,15):[];
 return <section className={styles.section}><div className={styles.heading}><div><h2>Melhores da Rodada {round}</h2>{live&&<span className={styles.live}>● Ao vivo</span>}</div><Link href="/pontuacao-atletas">Ver todos <ArrowRight/></Link></div>
  {firstRound?<p className={styles.feedback}>Os destaques dos atletas aparecerão após a primeira rodada.</p>:loading&&!data?<div className={styles.skeleton} aria-label="Carregando melhores atletas"/>:error&&!data?<p className={styles.feedback}>Não foi possível carregar os melhores atletas.</p>:athletes.length?<ol className={styles.list}>{athletes.map(({id,athlete},index)=><AthleteRow key={id} athlete={athlete} club={athlete.clube_id?data?.clubes?.[String(athlete.clube_id)]:undefined} rank={index+1}/>)}</ol>:<p className={styles.feedback}>Ainda não há pontuações disponíveis.</p>}
  {error&&data&&<small className={styles.updateError}>Exibindo a última atualização disponível.</small>}
 </section>;
}
function AthleteRow({athlete,club,rank}:{athlete:CartolaScoredAthlete;club?:CartolaClub;rank:number}){const photo=athlete.foto?.replace("FORMATO","140x140");const clubName=club&&athlete.clube_id?nomeClube(club,athlete.clube_id):null;const shield=club?escudoClube(club):null;return <li><strong className={styles.rank}>{rank}º</strong><span className={styles.photo}>{photo?<img src={photo} alt={`Foto de ${athlete.apelido}`} onError={event=>{event.currentTarget.style.display="none";event.currentTarget.nextElementSibling?.removeAttribute("hidden");}}/>:null}<i hidden={Boolean(photo)}><ImageOff/></i></span><span className={styles.identity}><span style={{display:"flex",alignItems:"center",gap:5,minWidth:0}}><b style={{overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{athlete.apelido}</b><Scouts athlete={athlete}/></span><small><em>{positions[athlete.posicao_id]??"--"}</em>{shield&&<img src={shield} alt={`Escudo do ${club?.nome??clubName}`}/>} {clubName}</small></span>{athlete.isMagoPick&&<span className={styles.mago}><Sparkles/> Dica do Mago</span>}<strong className={styles.points}>{points.format(athlete.pontuacao)} <small>pts</small></strong></li>}
function Scouts({athlete}:{athlete:CartolaScoredAthlete}){const scout=athlete.scout??{};const items=[{key:"G",icon:"⚽",singular:"gol",plural:"gols"},{key:"A",icon:"👟",singular:"assistência",plural:"assistências"},{key:"SG",icon:"SG",singular:"saldo de gols",plural:"saldos de gols"},{key:"GC",icon:"⚽",color:"#dc2626",singular:"gol contra",plural:"gols contra"},{key:"CA",icon:"🟨",singular:"cartão amarelo",plural:"cartões amarelos"},{key:"CV",icon:"🟥",singular:"cartão vermelho",plural:"cartões vermelhos"}].map(item=>({...item,count:scout[item.key]??0})).filter(item=>item.count>0);if(!items.length)return null;return <span style={{display:"inline-flex",alignItems:"center",flexShrink:0,gap:5,fontSize:11,fontStyle:"normal"}}>{items.map(item=><span key={item.key} title={`${item.count} ${item.count===1?item.singular:item.plural}`} aria-label={`${item.count} ${item.count===1?item.singular:item.plural}`}><span style={item.key==="SG"?{display:"inline-block",padding:"2px 5px",borderRadius:5,color:"#087b3d",background:"#dcfce7",fontSize:9,fontWeight:900}:item.color?{display:"inline-grid",placeItems:"center",width:17,height:17,borderRadius:"50%",background:item.color,fontSize:11}:undefined}>{item.icon}</span>{item.count>1&&<b>{item.count}</b>}</span>)}</span>}
